# Copyright (c) 2025 Joseph Hale
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: "iOS"

on:
  push:
    branches: ["master", "main", "ci"]

jobs:
  build:
    # Disable iOS builds since there won't be an iOS app until Loop Habit adds iOS support.
    if: false
    timeout-minutes: 25
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: Install Node dependencies
        run: npm install
      - name: Setup Cocoapods [cache]
        uses: actions/cache@v4
        id: cocoapods-cache
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-
      - name: Install CocoaPods
        run: npm run pods
      - name: Build Application
        run: |
          echo $SECRETS_TAR_GZ_B64 | base64 -d | tar -xz -C fastlane
          #  open secrets   | remove blanks   | grab values     |strip quotes| add the mask command           | redact from GitHub Actions logs
          cat fastlane/.env | grep -v '^\s*$' | cut -d "=" -f 2 |  tr -d '"' | awk '{print "::add-mask::"$0}' | xargs -n1 echo
          bundle exec fastlane ios build
          result=$?
          cat ${{ env.FASTLANE_LOG_PATH }}
          exit $?
        env:
          SECRETS_TAR_GZ_B64: ${{ secrets.SECRETS_TAR_GZ_B64 }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_LOG_PATH: /Users/runner/Library/Logs/gym/TodoistHabitSync-TodoistHabitSync.log
          RUBYOPT: '-rostruct' # Workaround for "NameError: uninitialized constant Fastlane::OpenStruct" (source: https://github.com/fastlane/fastlane/issues/21944#issuecomment-2045244250)